### ISSUE TITLE
Deleted ads don't disappear instantly

### ISSUE THREAD

**Issue by IvLaptev** [RTUITLab/StuDo-Android#4]
При удалении объявлений они остаются в списке до обновления

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/23360152/80793747-a2c3f180-8ba0-11ea-8880-6d27df499841.gif)

**Comment by Suput** [comment]
Для этих целей Back возвращает id объявления, которое было удалено. Таким образом, можно удалить объявление из своего локального списка без надобности делать новые запросы
